/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StorageManager;

//implementation("com.sun.net.httpserver:http:20070405")

import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;

import StorageManager.Endpoints.*;

public class App {

    public static void main(String[] args) {
        int port = 3030;
        System.out.println("Resource Manager Running on port: " + port);

        HttpServer server;

        try{
            //initialize server
            server = HttpServer.create(new InetSocketAddress("localhost",port), 0);

            server.createContext("/data", new Data());
            /*
            server.createContext("/start", new Start(stateController, settingsController));
            server.createContext("/stop", new Stop(stateController, settingsController));
            */
            server.setExecutor(null);
            server.start();
            }catch(Exception e){
            e.printStackTrace();
        }
    }
}
