package server.enumerators;

public enum TIMESTAMP_NAME {
	STORAGE_API_ENTRY,
	ENTRY_LIST_ENTRY,
	ENTRY_LIST_EXIT,
	DELAY_START,
	DELAY_END,
	READY_LIST_ENTRY,
	READY_LIST_EXIT,
	TRANSMITTER_ENTRY,
	TRANSMITTER_EXIT
}
