/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Application;

import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;

import distribution_generators.NaturalNumberDistributionGeneratorBuilder;
import distribution_generators.ParentNaturalNumberGenerator;
import endpoints.Start;
import endpoints.Stop;
import enumerators.PROGRAM_STATE;
import endpoints.Settings;


public class Server {

    public static void main(String[] args) {
        int port = 8000;
        System.out.println("Application Running on port: " + port);

        StateController stateController = new StateController();
        SettingsController settingsController = new SettingsController();
        settingsController.setStateController(stateController);
        ParentNaturalNumberGenerator generator;
        Application app = null;
        String receiverAddress;

        HttpServer server;

        try{
            //initialize server
            server = HttpServer.create(new InetSocketAddress("localhost",port), 0);
            server.createContext("/settings", new Settings(settingsController));
            server.createContext("/start", new Start(stateController, settingsController));
            server.createContext("/stop", new Stop(stateController, settingsController));
            server.setExecutor(null);
            server.start();


            while(stateController.getCurrentState() != PROGRAM_STATE.FINISHED){
                synchronized (settingsController.changeOfSettingsNotifier){
                    settingsController.changeOfSettingsNotifier.wait();
                }

                if(app!=null){
                    app.finishApplication();
                }

                generator = NaturalNumberDistributionGeneratorBuilder.build(settingsController);
                receiverAddress =  settingsController.getSetting("receiverAddress").toString();
                app = new Application(stateController,settingsController,generator,receiverAddress);
                Thread tp = new Thread(app);
                tp.start();

                System.out.println("Server: change of settings catched");
            }

            System.out.println("hello");
        }catch (Exception e) {
            e.printStackTrace();
        }

    }


}
